// Widths
localparam
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_CNST_CONF       = 15,
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_TEST_CONF       = 15,
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_POST_CONF       = 15,
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_PRE_CONF        = 6,
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_ARM             = 1,
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_TRIG_MODE       = 1,
  L_WIDTH_CUPPA_WVB_CONF_BUNDLE_CNST_RUN        = 1;

// Start position = Previous start + Width
localparam 
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_CNST_CONF       = 0,
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_TEST_CONF       = 15,
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_POST_CONF       = 30,
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_PRE_CONF        = 45,
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_ARM             = 51,
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_TRIG_MODE       = 52,
  L_START_POS_CUPPA_WVB_CONF_BUNDLE_CNST_RUN        = 53;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_CNST_CONF       = 14,
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_TEST_CONF       = 29,
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_POST_CONF       = 44,
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_PRE_CONF        = 50,
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_ARM             = 51,
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_TRIG_MODE       = 52,
  L_STOP_POS_CUPPA_WVB_CONF_BUNDLE_CNST_RUN        = 53;

// Zero pad width and bundle width
localparam L_WIDTH_CUPPA_WVB_CONF_BUNDLE_ZERO_PAD = 0;
localparam L_WIDTH_CUPPA_WVB_CONF_BUNDLE = 54;
