# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_assign.xdc

# XDC: C:/Users/atfie/watchman-ne1/wdc_zedboard/hdl/manual_io_constr.xdc

# XDC: C:/Users/atfie/watchman-ne1/wdc_zedboard/hdl/timing.xdc

# IP: ip/DIG0_MMCM/DIG0_MMCM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DIG0_MMCM || ORIG_REF_NAME==DIG0_MMCM} -quiet] -quiet
