// Widths
localparam
  L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_EVT_LTC         = 48,
  L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_START_ADDR      = 15,
  L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_STOP_ADDR       = 15,
  L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_TRIG_SRC        = 2,
  L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_CNST_RUN        = 1,
  L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_PRE_CONF        = 6;

// Start position = Previous start + Width
localparam 
  L_START_POS_CUPPA_WVB_HDR_BUNDLE_0_EVT_LTC         = 0,
  L_START_POS_CUPPA_WVB_HDR_BUNDLE_0_START_ADDR      = 48,
  L_START_POS_CUPPA_WVB_HDR_BUNDLE_0_STOP_ADDR       = 63,
  L_START_POS_CUPPA_WVB_HDR_BUNDLE_0_TRIG_SRC        = 78,
  L_START_POS_CUPPA_WVB_HDR_BUNDLE_0_CNST_RUN        = 80,
  L_START_POS_CUPPA_WVB_HDR_BUNDLE_0_PRE_CONF        = 81;

// Start position = Previous start + Width
localparam 
  L_STOP_POS_CUPPA_WVB_HDR_BUNDLE_0_EVT_LTC         = 47,
  L_STOP_POS_CUPPA_WVB_HDR_BUNDLE_0_START_ADDR      = 62,
  L_STOP_POS_CUPPA_WVB_HDR_BUNDLE_0_STOP_ADDR       = 77,
  L_STOP_POS_CUPPA_WVB_HDR_BUNDLE_0_TRIG_SRC        = 79,
  L_STOP_POS_CUPPA_WVB_HDR_BUNDLE_0_CNST_RUN        = 80,
  L_STOP_POS_CUPPA_WVB_HDR_BUNDLE_0_PRE_CONF        = 86;

// Zero pad width and bundle width
localparam L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0_ZERO_PAD = 0;
localparam L_WIDTH_CUPPA_WVB_HDR_BUNDLE_0 = 87;
