set_property PACKAGE_PIN Y9 [get_ports GCLK]
set_property PACKAGE_PIN T22 [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property PACKAGE_PIN T21 [get_ports LD1]
set_property PACKAGE_PIN U22 [get_ports LD2]
set_property IOSTANDARD LVCMOS33 [get_ports LD2]
set_property IOSTANDARD LVCMOS33 [get_ports LD7]
set_property IOSTANDARD LVCMOS33 [get_ports LD6]
set_property IOSTANDARD LVCMOS33 [get_ports LD5]
set_property IOSTANDARD LVCMOS33 [get_ports LD4]
set_property IOSTANDARD LVCMOS33 [get_ports LD3]
set_property PACKAGE_PIN U21 [get_ports LD3]
set_property PACKAGE_PIN V22 [get_ports LD4]
set_property PACKAGE_PIN W22 [get_ports LD5]
set_property PACKAGE_PIN U19 [get_ports LD6]
set_property PACKAGE_PIN U14 [get_ports LD7]
set_property IOSTANDARD LVCMOS33 [get_ports GCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LD1]

set_property DRIVE 12 [get_ports LD0]

set_property PACKAGE_PIN AA11 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RXD]
set_property PACKAGE_PIN Y11 [get_ports UART_TXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
